import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  fetchAssessorClasses,
  fetchAssessorOverview,
  storedAssessorId
} from "../../services/assessors";
import { ChevronRightIcon, CredentialIcon, FlagIcon, QueueIcon } from "./components/icons";
import { Chip, ScreenHeader, StatCard } from "./components/ui";

const HOW_GRADING_WORKS = {
  title: "How grading works here",
  body: "Assessments are generated by AI from the module's PDF, scoped to the course's Table of Specification. Every submission is checked by the AI first — you confirm the suggested score, override any item, or type a final grade yourself. If AI grading isn't available, for example when the token limit is reached, you grade the submission from scratch instead. A micro-credential is only issued after you approve it.",
  tags: ["AI checked", "Manual fallback", "Assessor decides"]
};

function ClassesPage() {
  const navigate = useNavigate();
  const [summary, setSummary] = useState({ toGrade: 0, aiFlagged: 0, credentials: 0 });
  const [classes, setClasses] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    let active = true;
    const assessorId = storedAssessorId();
    if (!assessorId) {
      setIsLoading(false);
      return undefined;
    }

    Promise.all([fetchAssessorOverview(assessorId), fetchAssessorClasses(assessorId)])
      .then(([overview, classList]) => {
        if (!active) return;
        setSummary(overview?.summary ?? { toGrade: 0, aiFlagged: 0, credentials: 0 });
        setClasses(classList);
      })
      .catch(() => {
        if (active) setClasses([]);
      })
      .finally(() => {
        if (active) setIsLoading(false);
      });

    return () => {
      active = false;
    };
  }, []);

  return (
    <>
      <ScreenHeader eyebrow="Assessor console" title="Classes" />

      <div className="assessor-body assessor-stack">
        <div className="stat-row">
          <StatCard
            value={summary.toGrade}
            label="To Grade"
            action="Open Queue"
            icon={<QueueIcon />}
            onAction={() => navigate("/assessor/queue")}
          />
          <StatCard
            value={summary.aiFlagged}
            label="AI Flagged"
            action="Review Flagged"
            icon={<FlagIcon />}
            onAction={() => navigate("/assessor/queue?filter=flagged")}
          />
          <StatCard
            value={summary.credentials}
            label="Credentials"
            action="Approve & Issue"
            icon={<CredentialIcon />}
            onAction={() => navigate("/assessor/credentials")}
          />

          <section className="explainer">
            <h2 className="explainer__title">{HOW_GRADING_WORKS.title}</h2>
            <p className="explainer__body">{HOW_GRADING_WORKS.body}</p>
            <div className="explainer__tags">
              {HOW_GRADING_WORKS.tags.map((tag, index) => (
                <Chip key={tag} tone={index % 2 === 0 ? "info" : "brand-soft"} dot>
                  {tag}
                </Chip>
              ))}
            </div>
          </section>
        </div>

        <section className="assessor-stack--tight" style={{ display: "flex", flexDirection: "column" }}>
          <h2 className="assessor-h2" style={{ marginBottom: "var(--sp-2)" }}>
            Your Classes
          </h2>

          {classes.map((course) => (
            <button
              type="button"
              key={course.id}
              className="class-row"
              onClick={() => navigate(`/assessor/classes/${course.id}`)}
            >
              <span className="class-row__lead">
                <span className="class-row__code" style={{ display: "block" }}>
                  {course.code}
                  {course.section ? ` · ${course.section}` : ""}
                </span>
                <span className="class-row__name" style={{ display: "block" }}>
                  {course.name}
                </span>
              </span>

              <span className="class-row__rule" aria-hidden="true" />

              <span className="class-row__students">{course.students} Students</span>

              <Chip tone={course.pending > 4 ? "brand" : "outline"}>
                {course.pending} to grade
              </Chip>

              <span className="class-row__chevron">
                <ChevronRightIcon size={20} />
              </span>
            </button>
          ))}

          {!isLoading && classes.length === 0 ? (
            <p className="assessor-meta" style={{ padding: "var(--sp-6)", textAlign: "center" }}>
              No classes are assigned to you yet.
            </p>
          ) : null}
        </section>
      </div>
    </>
  );
}

export default ClassesPage;
